name: Validate

on:
  push:
    branches: [ main, "legacy/**" ]
  pull_request:
    branches: [ main, "legacy/**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y zip libglib2.0-bin
      - name: Build
        run: |
          chmod +x tools/build.sh
          ./tools/build.sh
      - name: Validate zips
        run: |
          chmod +x tools/validate.sh
          ./tools/validate.sh
